### ISSUE TITLE
Typo in "aws secret key" config variable referece in AmazonS3ModuleImpl

### ISSUE THREAD

**Issue by prakashvadrevu** [0xbaadf00d/play-s3-module#1]
ReadMe of this module asks the dev to declare the aws secret key in the "conf" file with the key "**aws.secret.key**"

But, in the code (AmazonS3ModuleImpl) this is being read with the key "**aws.access.secret**". Hence, it isnt being resolved and the error "S3Module is not properly configured" is being thrown.

To align with the aws naming conventions, change the reference in the code to "aws.secret.key" and leave the doc as it is.

**Comment by prakashvadrevu** [comment]
@0xbaadf00d created a PR for this. Thanks!

**Comment by thibaultmeyer** [comment]
Thank your @prakashvadrevu. PR has been merged with success.
