### ISSUE TITLE
Ebean config: servers has type OBJECT rather than LIST

### ISSUE THREAD

**Issue by obykoo** [0xbaadf00d/play-s3-module#4]
```
ebean {
  servers {
    default {
      enhancement = ["models.*", "com.zero_x_baadf00d.play.module.aws.s3.ebean.S3FileModel"]
    }
  }
}
```
 (compile:playEbeanModels) com.typesafe.config.ConfigException$WrongType: application.conf @ conf/application.conf: 329: servers has type OBJECT rather than LIST

**Comment by thibaultmeyer** [comment]
Hi,

The Ebean enhancement configuration section of the README is based on [payintech/play-ebean](https://github.com/payintech/play-ebean). Which version of SBT Ebean are you using (project/plugins.sbt)?


**payintech/play-ebean** ([Github](https://github.com/payintech/play-ebean))
```
## Ebean
# https://github.com/payintech/play-ebean
# ~~~~~
ebean {
  servers {
    default {
      enhancement = ["models.*", "com.zero_x_baadf00d.play.module.aws.s3.ebean.S3FileModel"]
    }
  }
}
```

**playframework/play-ebean** ([Github](https://github.com/playframework/play-ebean))
```
## Ebean
# https://github.com/playframework/play-ebean
# ~~~~~
ebean {
  default= ["models.*", "com.zero_x_baadf00d.play.module.aws.s3.ebean.S3FileModel"]
}
```
